### ISSUE TITLE
[RTT] PM学习

### ISSUE THREAD

**Issue by chenyingchun0312** [supperthomas/bluetoothlover_doc#274]
https://club.rt-thread.org/ask/article/2282.html

https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/pm/pm

**Comment by chenyingchun0312** [comment]
pm_release
pm_release_all
pm_request
pm_module_release
pm_module_release_all
pm_module_request
pm_module_delay
pm_run
pm_dump

**Comment by chenyingchun0312** [comment]
cubemx 路径： C:\Users\cheny\STM32Cube\Repository

**Comment by chenyingchun0312** [comment]
接下来，先完成nordic pm驱动

**Comment by chenyingchun0312** [comment]
https://github.com/supperthomas/supperthomas_doc/issues/232

**Comment by chenyingchun0312** [comment]
[RT-Thread 电源管理组件-哔哩哔哩](https://b23.tv/KPn2NhK)

**Comment by supperthomas** [comment]
![Screenshot_2022-08-10-16-40-18-231_com.tencent.mm.jpg](https://user-images.githubusercontent.com/60349489/183856650-dadbed64-2914-4621-8254-948cfadf461f.jpg)

**Comment by supperthomas** [comment]
power down 之后，只能通过wakeup 唤醒，但是唤醒之后，会重新走reset流程。

**Comment by supperthomas** [comment]
power down之后，可以通过RTC定时器来唤醒，power down之后，RTC还可以独立工作。
