### ISSUE TITLE
west如何管理submodule

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/bluetoothlover_doc#448]

**Comment by chenyingchun0312** [comment]
[west_demo](https://github.com/chenyingchun0312/west_demo)


![image](https://user-images.githubusercontent.com/44871523/232278575-9486b395-e615-480e-9fee-51802500b007.png)

**Comment by supperthomas** [comment]
west 在发布的时候，要使用固定的commit hash值作为子repo的记号，
